### ISSUE TITLE
How to get or set a cell range Values with  a  array?

### ISSUE THREAD

**Issue by suisou** [DevExpress-Examples/spreadsheet-document-api-examples-e4339#5]
Does the spreadsheet can set/get  a range of cells value with a  array?

the demo code set a range cell value with the same value . but I want set the range cell with differert values  in one opration.
// Fill all cells in the range with 10.
worksheet.Range["B10:E10"].Value = 10;

**Comment by YuliaDX** [comment]
Hello,

It is much better to address this question to our Support and R&D Team. Please submit a ticket using our Support Center and our guys will do their best to assist you in this matter.
Here is an entry point:
https://www.devexpress.com/Support/Center/Question/Create
